In [4]:
## Numpy
## Generate an array consisting of 120 values using seed number 5
## Reshape the array to 2D of 12 Rows and 10 columns select the values from 5 to 8 on the rows and 4 to 6 on column
# broadcast 32 all over the selected value
# find the mean, meadian(25,75,85 percentile)

In [1]:
import numpy as np

In [3]:
# Step 1: of 120 values using seed number 5
#step2: reshape the array to a 2D array with 12 rows and 10 columns
# step 3: select the values from rows 5 to 8 and columns 4 to 6
#step 4: broadcast the value 32 all over the selected values
np.random.seed(5)
arr=np.random.randint(0,100,120)
arr_2D= arr.reshape(12,10)

selected_values= arr_2D[5:9,4:7]
selected_values[:]=32

#step 5: Calculate the mean,meadian,25,75 and 85th percentile
mean_value=np.mean(selected_values)
median_value=np.median(selected_values)
Average_value=np.average(selected_values)
percentile=np.percentile(selected_values,[25,75,85])

In [4]:
print("selected values: \n", selected_values)
print(Average_value)

selected values: 
 [[32 32 32]
 [32 32 32]
 [32 32 32]
 [32 32 32]]
32.0


In [36]:
print("Mean: \n", mean_value)

Mean: 
 32.0


In [37]:
print("Median: \n", median_value)

Median: 
 32.0


In [38]:
print("percentile: \n", percentile)

percentile: 
 [32. 32. 32.]


In [43]:
selected_values

array([[32, 32, 32],
       [32, 32, 32],
       [32, 32, 32],
       [32, 32, 32]])

In [44]:
print(arr)

[99 78 61 16 73  8 62 27 30 80  7 76 15 53 80 27 44 77 75 65 47 30 84 86
 18  9 41 62  1 82 16 78  5 58  0 80  4 36 51 27 31  2 68 38 83 19 18  7
 30 62 11 67 65 55 32 32 32 27 29 33 89 85  7 16 32 32 32 31  9 38 47 16
  5 34 32 32 32 13 31 32 76 44  5 14 32 32 32  0  7 86 16 64  8 90 44 37
 94 75  5 22 52 69 82 60 91 29 88 97 92 79 70 35 20 49 72 32 82 13 92 18]


In [45]:
print(arr_2D)

[[99 78 61 16 73  8 62 27 30 80]
 [ 7 76 15 53 80 27 44 77 75 65]
 [47 30 84 86 18  9 41 62  1 82]
 [16 78  5 58  0 80  4 36 51 27]
 [31  2 68 38 83 19 18  7 30 62]
 [11 67 65 55 32 32 32 27 29 33]
 [89 85  7 16 32 32 32 31  9 38]
 [47 16  5 34 32 32 32 13 31 32]
 [76 44  5 14 32 32 32  0  7 86]
 [16 64  8 90 44 37 94 75  5 22]
 [52 69 82 60 91 29 88 97 92 79]
 [70 35 20 49 72 32 82 13 92 18]]


# Question 2 

#create a data frame for client with the values ranging from 200000 to 500000 inclusive to be displayed for the last
#12 months (from january to december ), considering 31 days in each month.

In [1]:
import pandas as pd
import numpy as np

In [ ]:
id=np.arange(1,32)
column=["JANUARY","FEBRAUARY","MARCH","APRIL","MAY","JUNE","JULY","AUGUST","SEPTEMBER","OCTOBER","NOVEMBER","DECEMBER"]
np.random.seed(1)
values=np.random.randint(200000,500001,372)# it is 372 because 31 by 12 = 372 
values=values.reshape(31,12)## 31 days in a Month by 12 Months in a year
df=pd.DataFrame(data=values,index=id,columns=column)
df


In [4]:
data={'Month': [], 'Day': [],'Client_Value':[]}
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
days_per_month=31
data=np.random.randint(200000,500001,size=(days_per_month,12))
df=pd.DataFrame(data,index=range(1,days_per_month+1), columns=months)
df

January  February   March   April     May    June    July  August  \
1    435527    348942  290985  331246  348489  229507  434435  464127   
2    233170    435854  271015  323334  416028  287092  452298  423022   
3    217974    456029  475815  378522  457947  418044  303820  309713   
4    407776    409612  424358  409075  309086  416214  484123  351647   
5    263890    277842  462196  409018  372770  348947  487097  342059   
6    357483    353167  274566  368280  427933  495183  328691  494882   
7    316327    261608  401388  312913  465067  448408  283174  351424   
8    276276    294884  348824  460597  438614  218628  416752  252577   
9    221060    469504  409448  299079  213882  333252  224694  408050   
10   228029    327068  494215  241625  416553  286263  265377  241229   
11   470081    298549  256946  206172  289714  474250  250080  265505   
12   411808    259616  226776  253525  357987  387710  480096  327225   
13   294265    252000  466600  204742  392705  381791  256447  451267   
14   384019    305568  439162  303144  210336  203580  306835  214612   
15   395708    341696  319189  365371  252373  489185  482487  268711   
16   372063    383589  447846  361188  477058  359498  299796  411840   
17   249851    315440  353541  475307  274401  494728  306052  235367   
18   280830    281997  255211  403837  419989  335716  282700  464629   
19   323621    308012  305129  313207  228096  377807  236316  211560   
20   486416    205940  219545  211027  271646  289664  235882  369775   
21   267533    462616  374572  320275  266855  433440  429540  466594   
22   355642    497771  317445  254273  327155  227313  423186  374815   
23   406999    374175  214973  203487  340929  467497  231798  441689   
24   323656    251053  255217  431575  246424  421650  313874  265194   
25   323359    231284  387297  312310  277753  326319  316392  298632   
26   209022    315968  296810  350823  337731  390251  225515  367882   
27   485722    243531  417782  338369  259405  309627  233489  358856   
28   417551    342420  453115  272735  431898  225518  218891  342162   
29   359503    397057  274804  370693  395522  308889  229724  457811   
30   465361    476910  375121  263574  351872  344903  320605  232227   
31   292265    443618  238114  240781  223717  477977  490742  285533   

    September  October  November  December  
1      471587   471952    438245    238309  
2      290175   238392    336231    276572  
3      363911   241863    347923    224115  
4      391849   397997    219478    287014  
5      360691   450198    378959    224988  
6      242838   350975    244694    299437  
7      482864   334497    414098    209159  
8      257995   310969    393972    344204  
9      427916   243437    393888    294101  
10     351668   455014    405211    224230  
11     280645   231653    373422    359512  
12     494744   319142    325299    481514  
13     448220   480207    385922    265597  
14     469352   373944    355134    263620  
15     201449   443911    431530    223591  
16     469086   232643    252732    358572  
17     262447   242849    239815    288609  
18     479834   227386    201769    232025  
19     283260   326534    282098    237140  
20     368998   226618    424140    331090  
21     478655   343347    328769    235952  
22     212693   226796    282651    265343  
23     271123   470747    384888    214940  
24     211054   213845    256905    217042  
25     304662   343815    341168    367639  
26     308386   304267    247803    245898  
27     303462   448196    437894    340105  
28     224876   363365    270831    227988  
29     332075   353994    325182    328413  
30     483106   295464    416924    243199  
31     402144   251432    344791    452787

In [ ]:
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
days_per_month=[31,29,31