## Numpy

In [24]:
import numpy as np

In [2]:
arr1=np.array([80,90,70,50,100,89])

In [3]:
arr1

array([ 80,  90,  70,  50, 100,  89])

In [4]:
arr1.ndim
# this is what we use to check for the dimension of an array.

1

In [6]:
arr2=np.array([[87,45,90,100,58,90],[45.0,9.0,25.5,50.1,90.2,1.5]])
arr2

array([[ 87. ,  45. ,  90. , 100. ,  58. ,  90. ],
       [ 45. ,   9. ,  25.5,  50.1,  90.2,   1.5]])

In [12]:
arr2.ndim

2

In [10]:
## create 4 dimentional array
arr5=np.array([[[[87,45,90,100,58,90],[1,2,3,4,5,6],[6,5,4,3,2,1],[45.0,9.0,25.5,50.1,90.2,1.5]]]])
arr5

array([[[[ 87. ,  45. ,  90. , 100. ,  58. ,  90. ],
         [  1. ,   2. ,   3. ,   4. ,   5. ,   6. ],
         [  6. ,   5. ,   4. ,   3. ,   2. ,   1. ],
         [ 45. ,   9. ,  25.5,  50.1,  90.2,   1.5]]]])

In [4]:
arr5.shape

(1, 1, 4, 6)

In [13]:
## A variable.shape shows information about 
arr2.shape

(2, 6)

In [14]:
arr3=np.linspace(14,50)
arr3

array([14.        , 14.73469388, 15.46938776, 16.20408163, 16.93877551,
       17.67346939, 18.40816327, 19.14285714, 19.87755102, 20.6122449 ,
       21.34693878, 22.08163265, 22.81632653, 23.55102041, 24.28571429,
       25.02040816, 25.75510204, 26.48979592, 27.2244898 , 27.95918367,
       28.69387755, 29.42857143, 30.16326531, 30.89795918, 31.63265306,
       32.36734694, 33.10204082, 33.83673469, 34.57142857, 35.30612245,
       36.04081633, 36.7755102 , 37.51020408, 38.24489796, 38.97959184,
       39.71428571, 40.44897959, 41.18367347, 41.91836735, 42.65306122,
       43.3877551 , 44.12244898, 44.85714286, 45.59183673, 46.32653061,
       47.06122449, 47.79591837, 48.53061224, 49.26530612, 50.        ])

In [18]:
arr3.ndim


1

In [19]:
arr3.shape

(50,)

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.zeros(5)+10

array([10., 10., 10., 10., 10.])

In [12]:
np.ones(5)+9

array([10., 10., 10., 10., 10.])

In [14]:
# (1,100) it means starting from 1 to 100
arr4=np.arange(1,101)
arr4

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [13]:
# (1,100,2) it means starting from 1 to 100 but 2 is the number it skip to get to the next number
arr4=np.arange(1,101,2)
arr4

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [26]:
np.random.seed(1)
arr5=np.random.randint(20,101,100)
arr5

array([ 57,  32,  92,  29,  95,  25,  99,  84,  36,  21,  96,  91,  26,
        45,  70,  40,  38,  31,  48,  49,  34,  70,  88,  33,  29,  27,
        83,  81,  42,  77,  21,  20,  80,  28,  33,  67,  92,  50,  91,
        23,  90,  41,  69,  77,  23,  88,  44,  63,  96,  46,  72, 100,
        61,  35,  84,  88,  45,  27,  46,  45,  42,  29,  87,  43,  47,
        57,  77,  58,  28,  52,  54,  30,  43,  35,  45,  91,  94,  82,
        66,  52,  43,  75,  85,  97,  23,  20,  97,  26,  72,  90,  22,
        96,  41,  95,  27,  97,  92,  95,  96,  63])

In [3]:
np.random.seed(1)
arr6=np.random.randint(20,101,2)
arr6

array([57, 32])

In [23]:
np.random.seed(5)
arr9=np.random.randint(20,101,2)
arr9

array([98, 81])

In [20]:
arr7=np.arange(1,101,2)
arr7

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [31]:
arr5=arr5.reshape(50,2)
arr5

array([[ 57,  32],
       [ 92,  29],
       [ 95,  25],
       [ 99,  84],
       [ 36,  21],
       [ 96,  91],
       [ 26,  45],
       [ 70,  40],
       [ 38,  31],
       [ 48,  49],
       [ 34,  70],
       [ 88,  33],
       [ 29,  27],
       [ 83,  81],
       [ 42,  77],
       [ 21,  20],
       [ 80,  28],
       [ 33,  67],
       [ 92,  50],
       [ 91,  23],
       [ 90,  41],
       [ 69,  77],
       [ 23,  88],
       [ 44,  63],
       [ 96,  46],
       [ 72, 100],
       [ 61,  35],
       [ 84,  88],
       [ 45,  27],
       [ 46,  45],
       [ 42,  29],
       [ 87,  43],
       [ 47,  57],
       [ 77,  58],
       [ 28,  52],
       [ 54,  30],
       [ 43,  35],
       [ 45,  91],
       [ 94,  82],
       [ 66,  52],
       [ 43,  75],
       [ 85,  97],
       [ 23,  20],
       [ 97,  26],
       [ 72,  90],
       [ 22,  96],
       [ 41,  95],
       [ 27,  97],
       [ 92,  95],
       [ 96,  63]])

In [17]:
arr5[2:7,3:7]=50
arr5

array([[ 57,  32,  92,  29,  95,  25,  99,  84,  36,  21],
       [ 96,  91,  26,  45,  70,  40,  38,  31,  48,  49],
       [ 34,  70,  88,  50,  50,  50,  50,  81,  42,  77],
       [ 21,  20,  80,  50,  50,  50,  50,  50,  91,  23],
       [ 90,  41,  69,  50,  50,  50,  50,  63,  96,  46],
       [ 72, 100,  61,  50,  50,  50,  50,  27,  46,  45],
       [ 42,  29,  87,  50,  50,  50,  50,  58,  28,  52],
       [ 54,  30,  43,  35,  45,  91,  94,  82,  66,  52],
       [ 43,  75,  85,  97,  23,  20,  97,  26,  72,  90],
       [ 22,  96,  41,  95,  27,  97,  92,  95,  96,  63]])

In [18]:
arr5.ndim

2

In [19]:
arr5[arr5==43]

array([43, 43])

In [ ]:
arr5[arr5==43]